{
 "title": "Loki Dashboard - Quick Search",
 "description": "Loki logs panel with prometheus variables",
 "tags": [
  "Loki",
  "Kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_available{namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "Search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Deployment Specific Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Metrics Panel",
     "type": "graph",
     "description": "Deployment Metrics Panel",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", app=\"$deployment\"} [$__interval] |~ \"$Search\" ))"
      }
     ]
    },
    {
     "title": "Deployment Logs Panel",
     "type": "logs",
     "description": "Deployment Logs Panel",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=~\"$deployment\"} |~ \"$Search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Specific Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Metrics Panel",
     "type": "graph",
     "description": "Pod Metrics Panel",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} [$__interval] |~ \"$Search\" ))"
      }
     ]
    },
    {
     "title": "Pod Logs Panel",
     "type": "logs",
     "description": "Pod Logs Panel",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$Search\""
      }
     ]
    }
   ]
  }
 ]
}